// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mumsxgdukffsfclcevyx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11bXN4Z2R1a2Zmc2ZjbGNldnl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNTI1MDIsImV4cCI6MjA3MTgyODUwMn0.bhMqoaQCGK4nLGFs6xUSacU8ZNoeJpTdJ_6XmCOApm4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});